---
- hosts: all
  gather_facts: false
  tasks:
     - name: "Fazendo download do docker"
       shell: sudo wget https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.1.ce-3.el7.x86_64.rpm

     - name: "Instalando dependências do docker"
       shell: sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.42-1.gitad8f0f7.el7.noarch.rpm
     - name: "Instalando o docker"
       shell: sudo yum install docker-ce-18.06.1.ce-3.el7.x86_64.rpm -y
       ignore_errors: yes

     - name: "Instalando o docker-py"
       command: sudo pip install docker-py

     - name: "Startando o docker"
       command: sudo systemctl start docker

     - name: "Subindo DB"
       docker_container:
        name: "mysql-local"
        image: ambientum/mysql:5.7

        command: sleep infinity
        volumes:
          - ./mysql:/var/lib/mysql
        ports:
          - "3306:3306"
        env:
             MYSQL_ROOT_PASSWORD=root
             MYSQL_DATABASE=projeto_docker
             MYSQL_USER=docker
             MYSQL_PASSWORD=docker

     - name: "Subindo serviço web"
       docker_container:
        name: "apache-local"
        image: ambientum/php:7.0-apache
        command: sleep infinity
        volumes:
          - ./www/html:/var/www/app/public
        ports:
          - "8080:8080"
        links:
          - "mysql-local"

